"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { sampleUser } from "@/data/housing/sample-user";
import type { MaritalStatus, SubscriptionAccountType, UserProfile } from "@/lib/housing/types";
const STORAGE_KEY = "cheongyak-fit-profile-v1";
const steps = ["기본정보·거주", "주택·세대", "혼인·자녀", "청약통장", "소득·자산", "자금·기존대출", "희망조건", "분석"];
const money = (value: number) => Math.round(value / 10_000).toLocaleString();
export function ProfileWizard() {
  const router = useRouter(); const [profile, setProfile] = useState<UserProfile>(sampleUser); const [step, setStep] = useState(0); const [saved, setSaved] = useState(false);
  useEffect(() => { const savedProfile = window.localStorage.getItem(STORAGE_KEY); if (savedProfile) { try { queueMicrotask(() => setProfile(JSON.parse(savedProfile))); } catch { window.localStorage.removeItem(STORAGE_KEY); } } }, []);
  const set = <K extends keyof UserProfile>(key: K, value: UserProfile[K]) => setProfile(current => ({ ...current, [key]: value }));
  const number = (value: string) => Number(value.replace(/,/g, "")) || 0;
  const save = () => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(profile)); setSaved(true); };
  const finish = () => { save(); router.push("/housing/results"); };
  const textField = (label: string, value: string | number, onChange: (value: string) => void, type = "text") => <label className="housing-field">{label}<input type={type} value={value} onChange={event => onChange(event.target.value)} /></label>;
  return <div className="wizard"><ol className="wizard-steps">{steps.map((label, index) => <li className={index === step ? "is-current" : index < step ? "is-done" : ""} key={label}>{index + 1}. {label}</li>)}</ol><section className="housing-card wizard-card">
    {step === 0 && <><h2>기본정보와 거주</h2><div className="housing-form-grid">{textField("출생연도", profile.birthYear, value => set("birthYear", number(value)), "number")}{textField("시/도", profile.residenceRegion, value => set("residenceRegion", value))}{textField("시/군/구", profile.residenceCity, value => set("residenceCity", value))}{textField("전입일", profile.moveInDate, value => set("moveInDate", value), "date")}<label className="housing-field">세대 내 역할<select value={profile.householdRole} onChange={event => set("householdRole", event.target.value as UserProfile["householdRole"])}><option value="head">세대주</option><option value="member">세대원</option></select></label></div></>}
    {step === 1 && <><h2>주택 및 세대 조건</h2><div className="choice-grid"><Toggle label="현재 무주택입니다" value={profile.isHomeless} onChange={value => set("isHomeless", value)} /><Toggle label="과거 주택 소유 이력이 있습니다" value={profile.hasOwnedHouseBefore} onChange={value => set("hasOwnedHouseBefore", value)} /><Toggle label="분양권이 있습니다" value={profile.hasPreSaleRight} onChange={value => set("hasPreSaleRight", value)} /><Toggle label="입주권이 있습니다" value={profile.hasOccupancyRight} onChange={value => set("hasOccupancyRight", value)} /></div>{profile.isHomeless && textField("무주택 시작일", profile.homelessSince ?? "", value => set("homelessSince", value), "date")}</>}
    {step === 2 && <><h2>혼인 및 자녀</h2><div className="housing-form-grid"><label className="housing-field">혼인 상태<select value={profile.maritalStatus} onChange={event => set("maritalStatus", event.target.value as MaritalStatus)}><option value="single">미혼</option><option value="married">기혼</option><option value="engaged">예비부부</option><option value="divorced">이혼</option><option value="widowed">사별</option></select></label>{textField("자녀 수", profile.childrenCount, value => set("childrenCount", number(value)), "number")}{textField("미성년 자녀 수", profile.minorChildrenCount, value => set("minorChildrenCount", number(value)), "number")}</div>{profile.maritalStatus === "married" && <div className="housing-form-grid">{textField("혼인일", profile.marriageDate ?? "", value => set("marriageDate", value), "date")}{textField("배우자 연소득", profile.spouseIncome ?? 0, value => set("spouseIncome", number(value)), "number")}<label className="housing-field">배우자 주택 이력<select value={profile.spouseHousingHistory ?? ""} onChange={event => set("spouseHousingHistory", event.target.value)}><option value="">선택</option><option value="none">없음</option><option value="owned">소유 이력 있음</option></select></label></div>}<Toggle label="신생아 관련 특별공급 대상 여부를 확인할 수 있습니다" value={profile.newbornRelatedEligibility} onChange={value => set("newbornRelatedEligibility", value)} /></>}
    {step === 3 && <><h2>청약통장</h2><div className="housing-form-grid"><label className="housing-field">통장 종류<select value={profile.subscriptionAccount.type} onChange={event => set("subscriptionAccount", { ...profile.subscriptionAccount, type: event.target.value as SubscriptionAccountType })}><option value="housingSubscriptionSavings">주택청약종합저축</option><option value="youthHousingDream">청년주택드림청약통장</option><option value="subscriptionSavings">청약저축</option><option value="subscriptionDeposit">청약예금</option><option value="subscriptionInstallment">청약부금</option><option value="none">없음</option></select></label>{textField("개설일", profile.subscriptionAccount.openedAt ?? "", value => set("subscriptionAccount", { ...profile.subscriptionAccount, openedAt: value }), "date")}{textField("인정 납입회차", profile.subscriptionAccount.recognizedPaymentCount, value => set("subscriptionAccount", { ...profile.subscriptionAccount, recognizedPaymentCount: number(value) }), "number")}{textField("청약 인정금액 (원)", profile.subscriptionAccount.recognizedPaymentAmount, value => set("subscriptionAccount", { ...profile.subscriptionAccount, recognizedPaymentAmount: number(value) }), "number")}{textField("현재잔액 (원)", profile.subscriptionAccount.currentBalance, value => set("subscriptionAccount", { ...profile.subscriptionAccount, currentBalance: number(value) }), "number")}{textField("월 납입액 (원)", profile.subscriptionAccount.monthlyPayment, value => set("subscriptionAccount", { ...profile.subscriptionAccount, monthlyPayment: number(value) }), "number")}</div><p className="field-help">현재잔액과 청약 인정금액은 서로 다른 값으로 관리합니다.</p></>}
    {step === 4 && <><h2>소득과 자산</h2><div className="housing-form-grid">{textField("고용 형태", profile.income.employmentType, value => set("income", { ...profile.income, employmentType: value }))}{textField("연소득 (원)", profile.income.annualIncome, value => set("income", { ...profile.income, annualIncome: number(value) }), "number")}{textField("전년도 소득 (원)", profile.income.previousYearIncome, value => set("income", { ...profile.income, previousYearIncome: number(value) }), "number")}{textField("근속기간 (개월)", profile.income.employmentPeriod, value => set("income", { ...profile.income, employmentPeriod: number(value) }), "number")}{textField("가용 현금 (원)", profile.assets.availableCash, value => set("assets", { ...profile.assets, availableCash: number(value) }), "number")}{textField("예금·적금 (원)", profile.assets.savings, value => set("assets", { ...profile.assets, savings: number(value) }), "number")}{textField("금융자산 (원)", profile.assets.financialAssets, value => set("assets", { ...profile.assets, financialAssets: number(value) }), "number")}{textField("임차보증금 (원)", profile.assets.leaseDeposit, value => set("assets", { ...profile.assets, leaseDeposit: number(value) }), "number")}</div></>}
    {step === 5 && <><h2>자금 계획</h2><p className="field-help">가족 증여와 차용은 실제 조달 가능하다고 입력한 값만 참고 계산하며, 적법성 판단을 하지 않습니다.</p><div className="housing-form-grid">{textField("가족 증여 예정액 (원)", profile.familySupport.gift?.amount ?? 0, value => set("familySupport", { ...profile.familySupport, gift: { amount: number(value), previousGiftAmount: profile.familySupport.gift?.previousGiftAmount ?? 0 } }), "number")}{textField("기존 증여액 (원)", profile.familySupport.gift?.previousGiftAmount ?? 0, value => set("familySupport", { ...profile.familySupport, gift: { amount: profile.familySupport.gift?.amount ?? 0, previousGiftAmount: number(value) } }), "number")}{textField("가족 차용 예정액 (원)", profile.familySupport.loan?.amount ?? 0, value => set("familySupport", { ...profile.familySupport, loan: { amount: number(value), interestRate: profile.familySupport.loan?.interestRate ?? 0, repaymentYears: profile.familySupport.loan?.repaymentYears ?? 0, monthlyRepayment: profile.familySupport.loan?.monthlyRepayment ?? 0 } }), "number")}{textField("차용 이자율 (%)", profile.familySupport.loan?.interestRate ?? 0, value => set("familySupport", { ...profile.familySupport, loan: { amount: profile.familySupport.loan?.amount ?? 0, interestRate: number(value), repaymentYears: profile.familySupport.loan?.repaymentYears ?? 0, monthlyRepayment: profile.familySupport.loan?.monthlyRepayment ?? 0 } }), "number")}</div><p className="funding-preview">현재 입력 자금: 자기자금 {money(profile.assets.availableCash + profile.assets.savings + profile.assets.financialAssets)}만원 · 증여 {money(profile.familySupport.gift?.amount ?? 0)}만원 · 차용 {money(profile.familySupport.loan?.amount ?? 0)}만원</p></>}
    {step === 6 && <><h2>희망 조건</h2><div className="housing-form-grid">{textField("희망 지역 (쉼표로 구분)", profile.preferences.preferredRegions.join(", "), value => set("preferences", { ...profile.preferences, preferredRegions: value.split(",").map(item => item.trim()).filter(Boolean) }))}{textField("최대 분양가 (원)", profile.preferences.maxPrice, value => set("preferences", { ...profile.preferences, maxPrice: number(value) }), "number")}{textField("희망 면적 (㎡, 쉼표로 구분)", profile.preferences.preferredHousingSizes.join(", "), value => set("preferences", { ...profile.preferences, preferredHousingSizes: value.split(",").map(Number).filter(Boolean) }))}</div></>}
    {step === 7 && <><h2>분석 준비 완료</h2><p className="page-intro">입력값은 이 브라우저에만 저장됩니다. 주민등록번호, 계좌번호, 인증서, 은행 로그인 정보는 입력받지 않습니다.</p><button className="housing-primary" onClick={save}>프로필 저장하고 맞춤 분석 보기</button>{saved && <p className="success-note">브라우저에 저장했습니다. 이제 맞춤 결과에서 테스트 공고를 비교할 수 있습니다.</p>}</>}
    <div className="wizard-actions"><button className="housing-secondary" disabled={step === 0} onClick={() => setStep(current => current - 1)}>이전</button>{step < steps.length - 1 ? <button className="housing-primary" onClick={() => setStep(current => current + 1)}>다음</button> : <button className="housing-primary" onClick={finish}>저장하고 맞춤 결과 보기</button>}</div>
  </section></div>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="toggle"><input type="checkbox" checked={value} onChange={event => onChange(event.target.checked)} /> <span>{label}</span></label>; }
